# Vagrantfile

Vagrant.configure("2") do |config|
  # 定义虚拟机数量和基本配置
  (1..3).each do |i|
    config.vm.define "data_#{i}" do |web|
      web.vm.box = "centos/stream9"  # 使用 centos

      # 设置网络
      web.vm.network "private_network", ip: "192.168.33.#{i + 10}"

      # 可选：设置虚拟机内存和 CPU
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # 设置内存
        vb.cpus = 1         # 设置 CPU 数量
      end

      # 可选：设置同步文件夹
#     web.vm.synced_folder ".", "/vagrant_data"  # 将当前目录同步到虚拟机的 /vagrant_data

      # Provisioning: 安装 JDK 8 和 Docker
      web.vm.provision "shell", inline: <<-SHELL
          # 更新系统
          yum update -y

          # 安装 Java JDK 8
          yum install -y java-1.8.0-openjdk-devel

          # 安装 Docker
          yum install -y yum-utils
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y docker-ce docker-ce-cli containerd.io

          # 启动 Docker 服务
          systemctl start docker
          systemctl enable docker

          # 验证安装
          java -version
          docker --version
        SHELL
    end
  end
end